// Data page (#51): programmatic access. The ATTACH line first, then the Parquet files with a
// CSV export each, then the data dictionary rendered from datapackage.json (generated by
// build_marts from the same definitions it writes into the views file as COMMENT ON).
import { useEffect, useState, type ReactNode } from "react";
import { query, type Manifest } from "../db/duckdb";
import { downloadCsv } from "../lib/csv";

const SITE = "https://impact.bioconductor.org";
const PUBLIC_BASE = `${SITE}/data`;
const VIEWS_URL = `${PUBLIC_BASE}/bioc-intelligence.duckdb`;

interface Field {
  name: string;
  type: string;
  description: string;
}
interface Resource {
  name: string;
  path: string;
  bytes: number;
  description: string;
  schema: { fields: Field[] };
}
interface DataPackage {
  version: string;
  resources: Resource[];
  views: { name: string; source: string; description: string; sql: string }[];
}

const fmtBytes = (n: number) =>
  n >= 1 << 20 ? `${(n / (1 << 20)).toFixed(1)} MB` : `${Math.max(1, Math.round(n / 1024))} KB`;

// Every column cast to text so lists and dates export readably; the whole mart is pulled
// through DuckDB-WASM and written client-side.
async function exportCsv(file: string) {
  const cols = await query<{ column_name: string }>(`DESCRIBE SELECT * FROM '${file}'`);
  const list = cols.map((c) => `CAST("${c.column_name}" AS VARCHAR) AS "${c.column_name}"`);
  downloadCsv(file.replace(/\.parquet$/, ".csv"), await query(`SELECT ${list.join(", ")} FROM '${file}'`));
}

function Section({ id, title, children }: { id: string; title: string; children: ReactNode }) {
  return (
    <section id={id} className="mt-8">
      <h2 className="mb-3 text-lg font-semibold text-ink">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-neutral-400">{children}</div>
    </section>
  );
}

const Code = ({ label, children }: { label: string; children: string }) => (
  <div>
    <div className="text-xs font-semibold uppercase tracking-wide text-neutral-300">{label}</div>
    <pre className="mt-1 overflow-x-auto rounded-lg bg-neutral-500 p-3 text-xs text-neutral-50">
      <code>{children}</code>
    </pre>
  </div>
);

const A = ({ href, children }: { href: string; children: ReactNode }) => (
  <a className="text-primary-400 underline" href={href}>
    {children}
  </a>
);

const TH = "px-3 py-2 text-left text-xs font-semibold uppercase tracking-wide text-neutral-300";
const TD = "px-3 py-2 align-top";

function CsvButton({ file }: { file: string }) {
  const [state, setState] = useState<"idle" | "busy" | "error">("idle");
  return (
    <button
      type="button"
      disabled={state === "busy"}
      onClick={() => {
        setState("busy");
        exportCsv(file).then(
          () => setState("idle"),
          () => setState("error"),
        );
      }}
      className="rounded-md border border-neutral-100 px-2 py-1 text-xs font-medium text-neutral-400 hover:bg-neutral-75 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-teal disabled:opacity-50"
    >
      {state === "busy" ? "Exporting…" : state === "error" ? "Export failed, retry" : "CSV"}
    </button>
  );
}

export function Data({ manifest }: { manifest: Manifest | null }) {
  const [dp, setDp] = useState<DataPackage | null>(null);

  useEffect(() => {
    fetch(`${import.meta.env.BASE_URL}data/datapackage.json`)
      .then((r) => (r.ok ? r.json() : null))
      .then(setDp)
      .catch(() => setDp(null));
  }, []);

  const attach = `ATTACH '${VIEWS_URL}' AS bi (READ_ONLY);`;
  const bytes = new Map(dp?.resources.map((r) => [`${r.name}.parquet`, r.bytes]));
  const snapshot = manifest?.snapshot ?? dp?.version ?? "unknown";

  return (
    <div className="max-w-4xl">
      <h1 className="text-2xl font-semibold text-ink">Data</h1>
      <p className="mt-1 text-sm text-neutral-300">
        Everything on this site is public Parquet. Query it from DuckDB, R or Python, or download
        CSV. Snapshot {snapshot}.
      </p>

      <Section id="attach" title="Query it in one line">
        <p>
          <code>bioc-intelligence.duckdb</code> holds no data: it is a small file of documented
          views over the Parquet files below, so every column carries its definition. It opens in
          DuckDB 1.0 or newer, including the R package.
        </p>
        <Code label="SQL (DuckDB CLI)">{`${attach}
SELECT * FROM bi.package_impact WHERE package_name = 'limma';
SELECT view_name, comment FROM duckdb_views() WHERE database_name = 'bi';`}</Code>
        <Code label="R (duckdb)">{`library(duckdb)
con <- dbConnect(duckdb())
dbExecute(con, "INSTALL httpfs")
dbExecute(con, "LOAD httpfs")
dbExecute(con, "${attach}")
dbGetQuery(con, "SELECT * FROM bi.package_impact WHERE package_name = 'limma'")
# dbplyr: tbl(con, I("bi.package_impact"))`}</Code>
        <Code label="Python (duckdb)">{`import duckdb
con = duckdb.connect()
con.sql("INSTALL httpfs; LOAD httpfs")
con.sql("${attach}")
con.sql("SELECT * FROM bi.package_impact WHERE package_name = 'limma'").show()`}</Code>
        <p>
          There is one view per Parquet file (the name without the <code>mart_</code> prefix), plus
          views with the methodology built in:
        </p>
        <ul className="list-disc space-y-1 pl-5">
          {dp?.views.map((v) => (
            <li key={v.name}>
              <code>bi.{v.name}</code>: {v.description}
            </li>
          ))}
        </ul>
        <p>
          Recent DuckDB releases (verified on 1.5) also get two table macros:{" "}
          <code>SELECT * FROM bi.package(&apos;DESeq2&apos;)</code> (directory and impact for one
          package) and <code>SELECT * FROM bi.grant_report(&apos;U24CA289073&apos;)</code> (the
          packages a grant supports, with their impact). DuckDB 1.0 cannot call macros in an
          attached file; use the views.
        </p>
      </Section>

      <Section id="files" title="Parquet files">
        <p>Each file can also be read directly by URL, or exported here as CSV.</p>
        <div className="overflow-x-auto rounded-lg border border-primary-75 bg-white">
          <table className="w-full text-sm">
            <thead className="border-b border-primary-75 bg-primary-50">
              <tr>
                <th className={TH}>File</th>
                <th className={`${TH} text-right`}>Size</th>
                <th className={TH}>Export</th>
              </tr>
            </thead>
            <tbody>
              {manifest?.marts.map((m) => (
                <tr key={m} className="border-b border-neutral-75 last:border-0">
                  <td className={`${TD} break-all`}>
                    <A href={`${PUBLIC_BASE}/${m}`}>{`${PUBLIC_BASE}/${m}`}</A>
                  </td>
                  <td className={`${TD} whitespace-nowrap text-right tabular-nums`}>
                    {bytes.has(m) ? fmtBytes(bytes.get(m)!) : "—"}
                  </td>
                  <td className={TD}>
                    <CsvButton file={m} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p>
          Machine-readable description:{" "}
          <A href={`${PUBLIC_BASE}/datapackage.json`}>datapackage.json</A> (Frictionless Data
          Package).
        </p>
      </Section>

      <Section id="json" title="JSON and badges">
        <p>
          The same marts are rendered to static JSON at each deploy, for use without SQL. Start
          at <A href={`${SITE}/api/v1/index.json`}>{`${SITE}/api/v1/index.json`}</A> (snapshot,
          counts, every package name and grant id).
        </p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <code>{`${SITE}/api/v1/package/<name>.json`}</code>: directory and impact, papers,
            grants, people, funders, <code>confident_citations</code> (doi and CITATION links) and
            the last 36 months of downloads.
          </li>
          <li>
            <code>{`${SITE}/api/v1/grant/<core project number>.json`}</code>: the grant and its
            packages with their impact.
          </li>
          <li>
            <code>{`${SITE}/badges/<name>/downloads.json`}</code> and{" "}
            <code>citations.json</code>: shields.io endpoint badges (average monthly distinct IPs
            over the trailing 12 months; confident citations).
          </li>
        </ul>
        <Code label="Badge in a README (Markdown)">{`![usage](https://img.shields.io/endpoint?url=${SITE}/badges/limma/downloads.json)
![citations](https://img.shields.io/endpoint?url=${SITE}/badges/limma/citations.json)`}</Code>
      </Section>

      <Section id="dictionary" title="Data dictionary">
        {dp ? (
          dp.resources.map((r) => (
            <details key={r.name} className="rounded-lg border border-primary-75 bg-white">
              <summary className="cursor-pointer px-3 py-2">
                <code className="font-semibold text-ink">{r.name.replace(/^mart_/, "")}</code>{" "}
                <span className="text-neutral-400">{r.description}</span>
              </summary>
              <table className="w-full border-t border-primary-75 text-sm">
                <thead className="bg-primary-50">
                  <tr>
                    <th className={TH}>Column</th>
                    <th className={TH}>Type</th>
                    <th className={TH}>Definition</th>
                  </tr>
                </thead>
                <tbody>
                  {r.schema.fields.map((f) => (
                    <tr key={f.name} className="border-t border-neutral-75">
                      <td className={`${TD} font-mono text-xs`}>{f.name}</td>
                      <td className={`${TD} text-xs text-neutral-300`}>{f.type}</td>
                      <td className={TD}>{f.description}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </details>
          ))
        ) : (
          <p className="text-neutral-300">Loading the dictionary…</p>
        )}
      </Section>

      <Section id="cite" title="How to cite">
        <p className="rounded-lg border border-primary-75 bg-white p-4">
          Davis S. Bioconductor Intelligence: usage, publication and grant impact of Bioconductor
          packages. Snapshot {snapshot}. <A href={VIEWS_URL}>{VIEWS_URL}</A>
        </p>
        <p>
          Give the snapshot date: the files are replaced at each monthly refresh, so a number is
          reproducible only against its snapshot. Please also credit the upstream sources
          (Bioconductor, OpenAlex, NIH iCite, NIH RePORTER).
        </p>
      </Section>

      <Section id="hosting" title="Notes on hosting">
        <p>
          The files are served by GitHub Pages. Pages gzips <code>.parquet</code> and{" "}
          <code>.duckdb</code> for clients that ask for compression (every browser) and then
          applies HTTP Range requests to the compressed bytes, so a browser-based reader such as
          DuckDB-WASM cannot range-read them; fetch the whole file instead, as this site does. The
          views file is about 270 KB and the largest mart about 4 MB, so that is cheap. Native
          DuckDB (CLI, R, Python) does not ask for compression and reads them directly.
        </p>
        <p>
          The views point at these absolute URLs, so the views file always reads the current
          snapshot. Column names are additive between snapshots and are not renamed.
        </p>
      </Section>
    </div>
  );
}
